import React, { useMemo, useState } from 'react';
import { ArrowRight, BookOpen, Camera, Clapperboard, Cuboid, Layers3, MousePointer2, Palette, PenTool, Play, Search, Sparkles, Workflow } from 'lucide-react';
import { useLanguage } from '../context/LanguageContext';
import { KNOWLEDGE_DOMAINS, LEARNING_PATHS } from '../data/knowledgeStore';
import { KNOWLEDGE_CATALOG } from '../data/knowledgeCatalog';

interface Props { onOpenNode: (id: string) => void; }
const ICONS = [Palette, PenTool, MousePointer2, Camera, Clapperboard, Play, Cuboid, Layers3, Sparkles, BookOpen, Workflow, ArrowRight];

export const KnowledgeHubViewV2: React.FC<Props> = ({ onOpenNode }) => {
  const { lang } = useLanguage(); const isZh = lang === 'zh';
  const [query, setQuery] = useState(''); const [level, setLevel] = useState('all'); const [domain, setDomain] = useState('all');
  const filtered = useMemo(() => { const q = query.trim().toLowerCase(); return KNOWLEDGE_CATALOG.filter((node) => { const text = [node.title, node.titleEn, node.summary, node.summaryEn, ...node.tags, ...node.software].join(' ').toLowerCase(); return (!q || text.includes(q)) && (level === 'all' || node.level === level) && (domain === 'all' || node.domainId === domain); }); }, [query, level, domain]);
  return <section className="min-h-screen bg-[#11110F] text-[#F2F0E8]"><div className="max-w-[1440px] mx-auto px-6 lg:px-12 py-12 lg:py-20">
    <header className="border-b border-[#F2F0E8]/15 pb-10"><div className="text-[10px] font-mono tracking-[.18em] text-[#D8FF3E]">00 // KNOWLEDGE / CREATOR ENCYCLOPEDIA</div><div className="grid lg:grid-cols-[1.35fr_.65fr] gap-10 items-end mt-5"><h1 className="text-5xl md:text-7xl lg:text-[7rem] leading-[.86] font-black tracking-[-.06em]">{isZh ? <>创作者<br/><span className="text-[#D8FF3E]">知识百科</span></> : <>CREATOR<br/><span className="text-[#D8FF3E]">ENCYCLOPEDIA</span></>}</h1><div className="max-w-md text-sm leading-7 text-[#B5B1A8]">{isZh ? '不是软件教程堆，而是一张从原理到实践的创作知识地图。设计、摄影、视频、剪辑、AE、3D、声音、AI 与创作方法在这里互相连接。' : 'Not a pile of software tutorials. A connected map from principles to practice across design, photography, video, editing, motion, 3D, sound, AI and creative methodology.'}<div className="mt-5 font-mono text-[10px] text-[#F2F0E8]">{KNOWLEDGE_CATALOG.length} NODES · {KNOWLEDGE_DOMAINS.length} DOMAINS</div></div></div></header>
    <div className="py-7 border-b border-[#F2F0E8]/10 space-y-4"><div className="relative max-w-2xl"><Search className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-[#8B887F]"/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder={isZh ? '搜索知识、软件、方法… 例如 AE / 构图 / Blender' : 'Search concepts, software or methods…'} className="w-full bg-[#171714] border border-[#F2F0E8]/15 pl-11 pr-4 py-3.5 text-sm outline-none focus:border-[#D8FF3E]"/></div><div className="flex gap-2 overflow-x-auto pb-1 font-mono text-[10px]">{[['all', isZh ? '全部' : 'ALL'],['beginner',isZh?'入门':'BEGINNER'],['intermediate',isZh?'进阶':'INTERMEDIATE'],['advanced',isZh?'高级':'ADVANCED']].map(([id,label])=><button key={id} onClick={()=>setLevel(id)} className={`shrink-0 px-3 py-2 border ${level===id?'bg-[#D8FF3E] text-[#11110F] border-[#D8FF3E]':'border-[#F2F0E8]/15 text-[#8B887F]'}`}>{label}</button>)}</div><div className="flex gap-2 overflow-x-auto pb-1">{[['all',isZh?'全部领域':'ALL DOMAINS'],...KNOWLEDGE_DOMAINS.map(d=>[d.id,isZh?d.name:d.nameEn])].map(([id,label])=><button key={id} onClick={()=>setDomain(id)} className={`shrink-0 px-3 py-1.5 text-[10px] border ${domain===id?'border-[#D8FF3E] text-[#D8FF3E]':'border-[#F2F0E8]/10 text-[#77736B]'}`}>{label}</button>)}</div></div>
    <div className="pt-10 flex items-end justify-between"><div><span className="text-[10px] font-mono text-[#D8FF3E]">01 // KNOWLEDGE NODES</span><h2 className="text-3xl md:text-5xl font-bold mt-2">{isZh?'知识节点':'Knowledge Nodes'}</h2></div><span className="text-[10px] font-mono text-[#8B887F]">{filtered.length} / {KNOWLEDGE_CATALOG.length}</span></div>
    <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-px bg-[#F2F0E8]/10 border border-[#F2F0E8]/10 mt-6">{filtered.map(node=><button key={node.id} onClick={()=>onOpenNode(node.id)} className="text-left bg-[#11110F] p-6 min-h-[235px] hover:bg-[#181815] group relative"><div className="flex justify-between text-[10px] font-mono"><span className="text-[#D8FF3E]">{node.level.toUpperCase()}</span><span className="text-[#55534E]">{node.domainId}</span></div><h3 className="text-2xl font-bold mt-9">{isZh?node.title:node.titleEn}</h3><p className="text-sm text-[#8B887F] leading-6 mt-3">{isZh?node.summary:node.summaryEn}</p><div className="flex flex-wrap gap-1.5 mt-5">{node.tags.slice(0,3).map(tag=><span key={tag} className="px-2 py-1 border border-[#F2F0E8]/10 text-[9px] font-mono text-[#77736B]">{tag}</span>)}</div><ArrowRight className="absolute bottom-6 right-6 w-4 h-4 text-[#55534E] group-hover:text-[#D8FF3E] group-hover:translate-x-1 transition-all"/></button>)}</div>
    <div className="mt-20"><span className="text-[10px] font-mono text-[#D8FF3E]">02 // LEARNING PATHS</span><h2 className="text-4xl md:text-6xl font-black tracking-[-.04em] mt-3">{isZh?'从零开始，不靠猜。':'Learn by path, not by chance.'}</h2><div className="grid md:grid-cols-2 gap-2 mt-8">{LEARNING_PATHS.map((path,i)=><button key={path.id} onClick={()=>path.steps[0]&&onOpenNode(path.steps[0])} className="text-left border border-[#F2F0E8]/10 p-6 hover:border-[#D8FF3E]/40 group"><div className="flex justify-between"><span className="font-mono text-[10px] text-[#D8FF3E]">0{i+1}</span><span className="font-mono text-[10px] text-[#55534E]">{path.steps.length} STEPS</span></div><h3 className="text-2xl font-bold mt-8">{isZh?path.title:path.titleEn}</h3><p className="text-sm text-[#8B887F] mt-3 leading-6">{isZh?path.description:path.descriptionEn}</p><div className="mt-5 flex flex-wrap gap-2">{path.domainIds.map(id=>{const d=KNOWLEDGE_DOMAINS.find(x=>x.id===id);return <span key={id} className="text-[9px] font-mono text-[#77736B]">#{isZh?d?.name:d?.nameEn}</span>})}</div></button>)}</div></div>
    <div className="mt-20 grid md:grid-cols-3 gap-px bg-[#F2F0E8]/10 border border-[#F2F0E8]/10">{KNOWLEDGE_DOMAINS.slice(0,3).map((d,i)=>{const Icon=ICONS[i];return <div key={d.id} className="bg-[#11110F] p-7"><Icon className="w-5 h-5 text-[#D8FF3E]"/><div className="text-[10px] font-mono text-[#8B887F] mt-8">DOMAIN {String(i+1).padStart(2,'0')}</div><h3 className="text-2xl font-bold mt-2">{isZh?d.name:d.nameEn}</h3><p className="text-sm text-[#8B887F] mt-3">{isZh?d.description:d.descriptionEn}</p></div>})}</div>
  </div></section>;
};
