import React, { useMemo, useState } from 'react';
import { Calculator, Camera, Copy, Ratio, Sparkles, WandSparkles } from 'lucide-react';
import { useLanguage } from '../context/LanguageContext';

const ratios = [{ name:'16:9', a:16,b:9 },{name:'9:16',a:9,b:16},{name:'4:3',a:4,b:3},{name:'3:4',a:3,b:4},{name:'1:1',a:1,b:1},{name:'21:9',a:21,b:9}];
function gcd(a:number,b:number):number{return b?gcd(b,a%b):a;}
function ratioFrom(w:number,h:number){const g=gcd(Math.max(1,w),Math.max(1,h));return `${Math.round(w/g)}:${Math.round(h/g)}`;}

export const ToolsHubViewV2: React.FC = () => {
  const { lang } = useLanguage(); const isZh=lang==='zh'; const [w,setW]=useState(1920); const [h,setH]=useState(1080); const [hex,setHex]=useState('#D8FF3E'); const [prompt,setPrompt]=useState('电影感城市夜景，人物在雨中行走'); const [copied,setCopied]=useState(false);
  const computedRatio=useMemo(()=>ratioFrom(w,h),[w,h]);
  const harmony=useMemo(()=>{let x=hex.replace('#',''); if(x.length!==6)return ['#D8FF3E']; const r=parseInt(x.slice(0,2),16),g=parseInt(x.slice(2,4),16),b=parseInt(x.slice(4,6),16); const hsl=(rr:number,gg:number,bb:number)=>{const mx=Math.max(rr,gg,bb)/255,mn=Math.min(rr,gg,bb)/255;let hh=0;const d=mx-mn;if(d){if(mx===rr)hh=((gg-bb)/255/d)%6;else if(mx===gg)hh=(bb-rr)/255/d+2;else hh=(rr-gg)/255/d+4;hh=Math.round(hh*60);if(hh<0)hh+=360;}return hh;}; const rgb=(hh:number)=>{const c=1,s=1,l=.55,x=c*(1-Math.abs((hh/60)%2-1));let rr=0,gg=0,bb=0;if(hh<60)[rr,gg]=[c,x];else if(hh<120)[rr,gg]=[x,c];else if(hh<180)[gg,bb]=[c,x];else if(hh<240)[gg,bb]=[x,c];else if(hh<300)[rr,bb]=[x,c];else[rr,bb]=[c,x];const m=l-c/2;return '#'+[rr,gg,bb].map(v=>Math.round((v+m)*255).toString(16).padStart(2,'0')).join('').toUpperCase();};const base=hsl(r,g,b);return [hex.toUpperCase(),rgb((base+30)%360),rgb((base+180)%360),rgb((base+210)%360)];},[hex]);
  const generatedPrompt=`${prompt}；主体清晰，电影级构图，35mm 镜头，浅景深，体积光，低调高对比，受控的色彩层级，细腻材质，真实光影，16:9 横构图`;
  const copy=async()=>{try{await navigator.clipboard.writeText(generatedPrompt);setCopied(true);setTimeout(()=>setCopied(false),1200)}catch{}};
  return <section className="min-h-screen bg-[#11110F] text-[#F2F0E8]"><div className="max-w-[1440px] mx-auto px-6 lg:px-12 py-12 lg:py-20"><div className="text-[10px] font-mono tracking-[.18em] text-[#D8FF3E]">03 // CREATOR TOOLS</div><h1 className="text-5xl md:text-7xl lg:text-[7rem] font-black tracking-[-.06em] leading-[.86] mt-4">{isZh?<>创作<br/><span className="text-[#D8FF3E]">工具箱</span></>:<>CREATOR<br/><span className="text-[#D8FF3E]">TOOLS</span></>}</h1><p className="max-w-2xl text-[#8B887F] leading-7 mt-7">{isZh?'小工具不是附属品，而是把百科知识变成行动的入口。所有工具优先在浏览器本地运行。':'Small tools turn encyclopedia knowledge into action. Utilities run locally in the browser whenever possible.'}</p>
    <div className="grid lg:grid-cols-2 gap-px bg-[#F2F0E8]/10 border border-[#F2F0E8]/10 mt-14">
      <div className="bg-[#11110F] p-7 md:p-9"><div className="flex justify-between"><Ratio className="w-5 h-5 text-[#D8FF3E]"/><span className="text-[10px] font-mono text-[#55534E]">TOOL 01</span></div><h2 className="text-2xl font-bold mt-10">{isZh?'画幅比例计算器':'Aspect Ratio Calculator'}</h2><div className="grid grid-cols-2 gap-3 mt-7"><label className="text-[10px] font-mono text-[#8B887F]">WIDTH<input type="number" value={w} onChange={e=>setW(Number(e.target.value)||1)} className="mt-2 w-full bg-[#171714] border border-[#F2F0E8]/15 p-3 text-sm"/></label><label className="text-[10px] font-mono text-[#8B887F]">HEIGHT<input type="number" value={h} onChange={e=>setH(Number(e.target.value)||1)} className="mt-2 w-full bg-[#171714] border border-[#F2F0E8]/15 p-3 text-sm"/></label></div><div className="mt-6 border border-[#D8FF3E]/25 bg-[#D8FF3E]/5 p-5"><div className="text-[10px] font-mono text-[#8B887F]">RATIO</div><div className="text-4xl font-black text-[#D8FF3E] mt-1">{computedRatio}</div></div><div className="flex flex-wrap gap-2 mt-5">{ratios.map(r=><button key={r.name} onClick={()=>{setW(1920);setH(Math.round(1920*r.b/r.a))}} className="px-3 py-1.5 border border-[#F2F0E8]/10 text-[10px] font-mono text-[#8B887F] hover:text-[#D8FF3E]">{r.name}</button>)}</div></div>
      <div className="bg-[#11110F] p-7 md:p-9"><div className="flex justify-between"><Sparkles className="w-5 h-5 text-[#D8FF3E]"/><span className="text-[10px] font-mono text-[#55534E]">TOOL 02</span></div><h2 className="text-2xl font-bold mt-10">{isZh?'配色探索器':'Color Harmony Explorer'}</h2><div className="flex gap-3 mt-7"><input type="color" value={hex} onChange={e=>setHex(e.target.value)} className="w-14 h-12 bg-transparent"/><input value={hex} onChange={e=>setHex(e.target.value)} className="flex-1 bg-[#171714] border border-[#F2F0E8]/15 px-4 text-sm font-mono uppercase"/></div><div className="grid grid-cols-4 gap-2 mt-6">{harmony.map(c=><div key={c}><div className="h-20 border border-white/10" style={{background:c}}/><div className="text-[9px] font-mono text-[#77736B] mt-2">{c}</div></div>)}</div><p className="text-xs text-[#8B887F] mt-5">{isZh?'基于色相关系生成一组可用于视觉设计的探索色。':'Generate exploratory colors from hue relationships for visual design.'}</p></div>
      <div className="bg-[#11110F] p-7 md:p-9"><div className="flex justify-between"><WandSparkles className="w-5 h-5 text-[#D8FF3E]"/><span className="text-[10px] font-mono text-[#55534E]">TOOL 03</span></div><h2 className="text-2xl font-bold mt-10">{isZh?'AI Prompt 视觉增强器':'AI Prompt Visual Enhancer'}</h2><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} className="mt-7 w-full min-h-28 bg-[#171714] border border-[#F2F0E8]/15 p-4 text-sm leading-6 resize-y"/><div className="mt-4 border border-[#F2F0E8]/10 p-4 text-sm leading-6 text-[#B5B1A8]">{generatedPrompt}</div><button onClick={copy} className="mt-4 inline-flex items-center gap-2 px-4 py-2 bg-[#D8FF3E] text-[#11110F] text-[10px] font-mono font-bold"><Copy className="w-3.5 h-3.5"/>{copied?(isZh?'已复制':'COPIED'):(isZh?'复制 Prompt':'COPY PROMPT')}</button></div>
      <div className="bg-[#11110F] p-7 md:p-9"><div className="flex justify-between"><Camera className="w-5 h-5 text-[#D8FF3E]"/><span className="text-[10px] font-mono text-[#55534E]">TOOL 04</span></div><h2 className="text-2xl font-bold mt-10">{isZh?'摄影参数速查':'Photography Quick Reference'}</h2><div className="space-y-2 mt-7">{[['快门','1/50–1/250','动作与运动模糊'],['光圈','f/1.4–f/2.8','主体分离与景深'],['ISO','100–800','曝光与噪点'],['帧率','24 / 25 / 30 / 60 fps','视频运动观感']].map(([a,b,c])=><div key={a} className="grid grid-cols-[70px_110px_1fr] gap-3 border-b border-[#F2F0E8]/10 py-3 text-xs"><span className="text-[#D8FF3E] font-mono">{a}</span><span className="font-mono">{b}</span><span className="text-[#8B887F]">{c}</span></div>)}</div><div className="mt-5 text-[10px] text-[#55534E] font-mono"><Calculator className="inline w-3 h-3 mr-1"/>参数只是起点，实际曝光与风格取决于场景。</div></div>
    </div></div></section>;
};
